### ISSUE TITLE
Add a devcontainer.json file

### ISSUE THREAD

**Issue by julienbrg** [w3hc/gcfa-contracts#54]
Add a devcontainer.json file so that anyone can use codespaces with the same Node.js version. 

https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/adding-a-dev-container-configuration/introduction-to-dev-containers

**Comment by ArshErgon** [comment]
hey @julienbrg will you assign this to me?

**Comment by julienbrg** [comment]
@ArshErgon My review: https://github.com/w3hc/gcfa-contracts/pull/55#pullrequestreview-1459474846

**Comment by julienbrg** [comment]
Fixed by https://github.com/w3hc/gcfa-contracts/commit/29a87876ea58412b7e40f97a477ac22da04ab757#diff-2c8effdf840690ccb88c7e21e56148978c6adb2c6926530c58ff0e47a9588b44
